name: Update db.json

on:
  repository_dispatch:
    types: [update-db]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update db.json
        run: |
          echo '{"key": "value"}' | base64 > content.txt
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d @- \
            https://api.github.com/repos/whashby/thelamegame/contents/data/db.json <<EOF
{
  "message": "Updating db.json",
  "content": "$(cat content.txt)"
}
EOF
